name: summarizer_example
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  flutter_local_summarizer:
    path: ../

dev_dependencies:
  # Collection of lint rules for Dart and Flutter projects.
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  test: ^1.25.2

flutter:
  uses-material-design: true
#  assets:
#    - assets/
