name: flutter_local_summarizer
description: "Flutter package to summarize text using Falconsai/text_summarization"
version: 0.0.1
repository: https://github.com/guyluz11/flutter_local_summarizer
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  langchain_tiktoken:
    git:
      url: https://github.com/guyluz11/langchain_tiktoken.git
      ref: main
  onnxruntime:
    path: ../onnxruntime_flutter
  path_provider: ^2.1.5


dev_dependencies:
  # Collection of lint rules for Dart and Flutter projects.
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  test: ^1.25.2

# The following section is specific to Flutter packages.
flutter:
